global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"]
        labels:
          service: "go-backend"

  - job_name: "matching-engine"
    metrics_path: /metrics
    static_configs:
      - targets: ["matching-engine:8081"]
        labels:
          service: "matching-engine"

  - job_name: "backend-health"
    metrics_path: /health
    scrape_interval: 30s
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "matching-health"
    metrics_path: /health
    scrape_interval: 30s
    static_configs:
      - targets: ["matching-engine:8081"]
